// This is an auto-generated file.

const MachinaModels = require("../_MachinaModels.js")

module.exports = async (struct) => {
    struct.listing_1 = {
        listingId: MachinaModels.getUint64(struct.data, 0),
        retainerId: MachinaModels.getUint64(struct.data, 8),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 16),
        artisanId: MachinaModels.getUint64(struct.data, 24),
        pricePerUnit: MachinaModels.getUint32(struct.data, 32),
        totalTax: MachinaModels.getUint32(struct.data, 36),
        itemQuantity: MachinaModels.getUint32(struct.data, 40),
        itemId: MachinaModels.getUint32(struct.data, 44),
        lastReviewTime: MachinaModels.getUint16(struct.data, 48),
        containerId: MachinaModels.getUint16(struct.data, 50),
        slotId: MachinaModels.getUint32(struct.data, 52),
        durability: MachinaModels.getUint16(struct.data, 56),
        spiritBond: MachinaModels.getUint16(struct.data, 58),
        materiaValue_1: MachinaModels.getUint16(struct.data, 60),materiaValue_2: MachinaModels.getUint16(struct.data, 62),materiaValue_3: MachinaModels.getUint16(struct.data, 64),materiaValue_4: MachinaModels.getUint16(struct.data, 66),materiaValue_5: MachinaModels.getUint16(struct.data, 68),
        retainerName: String.fromCodePoint(struct.data.slice(70, 71)),
        playerName: String.fromCodePoint(struct.data.slice(71, 72)),
        hq: struct.data[72],
        materiaCount: struct.data[73],
        onMannequin: struct.data[74],
        retainerCity: struct.data[75],
        dyeId: MachinaModels.getUint16(struct.data, 76),
    };
    struct.listing_2 = {
        listingId: MachinaModels.getUint64(struct.data, 78),
        retainerId: MachinaModels.getUint64(struct.data, 86),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 94),
        artisanId: MachinaModels.getUint64(struct.data, 102),
        pricePerUnit: MachinaModels.getUint32(struct.data, 110),
        totalTax: MachinaModels.getUint32(struct.data, 114),
        itemQuantity: MachinaModels.getUint32(struct.data, 118),
        itemId: MachinaModels.getUint32(struct.data, 122),
        lastReviewTime: MachinaModels.getUint16(struct.data, 126),
        containerId: MachinaModels.getUint16(struct.data, 128),
        slotId: MachinaModels.getUint32(struct.data, 130),
        durability: MachinaModels.getUint16(struct.data, 134),
        spiritBond: MachinaModels.getUint16(struct.data, 136),
        materiaValue_1: MachinaModels.getUint16(struct.data, 138),materiaValue_2: MachinaModels.getUint16(struct.data, 140),materiaValue_3: MachinaModels.getUint16(struct.data, 142),materiaValue_4: MachinaModels.getUint16(struct.data, 144),materiaValue_5: MachinaModels.getUint16(struct.data, 146),
        retainerName: String.fromCodePoint(struct.data.slice(148, 149)),
        playerName: String.fromCodePoint(struct.data.slice(149, 150)),
        hq: struct.data[150],
        materiaCount: struct.data[151],
        onMannequin: struct.data[152],
        retainerCity: struct.data[153],
        dyeId: MachinaModels.getUint16(struct.data, 154),
    };
    struct.listing_3 = {
        listingId: MachinaModels.getUint64(struct.data, 156),
        retainerId: MachinaModels.getUint64(struct.data, 164),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 172),
        artisanId: MachinaModels.getUint64(struct.data, 180),
        pricePerUnit: MachinaModels.getUint32(struct.data, 188),
        totalTax: MachinaModels.getUint32(struct.data, 192),
        itemQuantity: MachinaModels.getUint32(struct.data, 196),
        itemId: MachinaModels.getUint32(struct.data, 200),
        lastReviewTime: MachinaModels.getUint16(struct.data, 204),
        containerId: MachinaModels.getUint16(struct.data, 206),
        slotId: MachinaModels.getUint32(struct.data, 208),
        durability: MachinaModels.getUint16(struct.data, 212),
        spiritBond: MachinaModels.getUint16(struct.data, 214),
        materiaValue_1: MachinaModels.getUint16(struct.data, 216),materiaValue_2: MachinaModels.getUint16(struct.data, 218),materiaValue_3: MachinaModels.getUint16(struct.data, 220),materiaValue_4: MachinaModels.getUint16(struct.data, 222),materiaValue_5: MachinaModels.getUint16(struct.data, 224),
        retainerName: String.fromCodePoint(struct.data.slice(226, 227)),
        playerName: String.fromCodePoint(struct.data.slice(227, 228)),
        hq: struct.data[228],
        materiaCount: struct.data[229],
        onMannequin: struct.data[230],
        retainerCity: struct.data[231],
        dyeId: MachinaModels.getUint16(struct.data, 232),
    };
    struct.listing_4 = {
        listingId: MachinaModels.getUint64(struct.data, 234),
        retainerId: MachinaModels.getUint64(struct.data, 242),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 250),
        artisanId: MachinaModels.getUint64(struct.data, 258),
        pricePerUnit: MachinaModels.getUint32(struct.data, 266),
        totalTax: MachinaModels.getUint32(struct.data, 270),
        itemQuantity: MachinaModels.getUint32(struct.data, 274),
        itemId: MachinaModels.getUint32(struct.data, 278),
        lastReviewTime: MachinaModels.getUint16(struct.data, 282),
        containerId: MachinaModels.getUint16(struct.data, 284),
        slotId: MachinaModels.getUint32(struct.data, 286),
        durability: MachinaModels.getUint16(struct.data, 290),
        spiritBond: MachinaModels.getUint16(struct.data, 292),
        materiaValue_1: MachinaModels.getUint16(struct.data, 294),materiaValue_2: MachinaModels.getUint16(struct.data, 296),materiaValue_3: MachinaModels.getUint16(struct.data, 298),materiaValue_4: MachinaModels.getUint16(struct.data, 300),materiaValue_5: MachinaModels.getUint16(struct.data, 302),
        retainerName: String.fromCodePoint(struct.data.slice(304, 305)),
        playerName: String.fromCodePoint(struct.data.slice(305, 306)),
        hq: struct.data[306],
        materiaCount: struct.data[307],
        onMannequin: struct.data[308],
        retainerCity: struct.data[309],
        dyeId: MachinaModels.getUint16(struct.data, 310),
    };
    struct.listing_5 = {
        listingId: MachinaModels.getUint64(struct.data, 312),
        retainerId: MachinaModels.getUint64(struct.data, 320),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 328),
        artisanId: MachinaModels.getUint64(struct.data, 336),
        pricePerUnit: MachinaModels.getUint32(struct.data, 344),
        totalTax: MachinaModels.getUint32(struct.data, 348),
        itemQuantity: MachinaModels.getUint32(struct.data, 352),
        itemId: MachinaModels.getUint32(struct.data, 356),
        lastReviewTime: MachinaModels.getUint16(struct.data, 360),
        containerId: MachinaModels.getUint16(struct.data, 362),
        slotId: MachinaModels.getUint32(struct.data, 364),
        durability: MachinaModels.getUint16(struct.data, 368),
        spiritBond: MachinaModels.getUint16(struct.data, 370),
        materiaValue_1: MachinaModels.getUint16(struct.data, 372),materiaValue_2: MachinaModels.getUint16(struct.data, 374),materiaValue_3: MachinaModels.getUint16(struct.data, 376),materiaValue_4: MachinaModels.getUint16(struct.data, 378),materiaValue_5: MachinaModels.getUint16(struct.data, 380),
        retainerName: String.fromCodePoint(struct.data.slice(382, 383)),
        playerName: String.fromCodePoint(struct.data.slice(383, 384)),
        hq: struct.data[384],
        materiaCount: struct.data[385],
        onMannequin: struct.data[386],
        retainerCity: struct.data[387],
        dyeId: MachinaModels.getUint16(struct.data, 388),
    };
    struct.listing_6 = {
        listingId: MachinaModels.getUint64(struct.data, 390),
        retainerId: MachinaModels.getUint64(struct.data, 398),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 406),
        artisanId: MachinaModels.getUint64(struct.data, 414),
        pricePerUnit: MachinaModels.getUint32(struct.data, 422),
        totalTax: MachinaModels.getUint32(struct.data, 426),
        itemQuantity: MachinaModels.getUint32(struct.data, 430),
        itemId: MachinaModels.getUint32(struct.data, 434),
        lastReviewTime: MachinaModels.getUint16(struct.data, 438),
        containerId: MachinaModels.getUint16(struct.data, 440),
        slotId: MachinaModels.getUint32(struct.data, 442),
        durability: MachinaModels.getUint16(struct.data, 446),
        spiritBond: MachinaModels.getUint16(struct.data, 448),
        materiaValue_1: MachinaModels.getUint16(struct.data, 450),materiaValue_2: MachinaModels.getUint16(struct.data, 452),materiaValue_3: MachinaModels.getUint16(struct.data, 454),materiaValue_4: MachinaModels.getUint16(struct.data, 456),materiaValue_5: MachinaModels.getUint16(struct.data, 458),
        retainerName: String.fromCodePoint(struct.data.slice(460, 461)),
        playerName: String.fromCodePoint(struct.data.slice(461, 462)),
        hq: struct.data[462],
        materiaCount: struct.data[463],
        onMannequin: struct.data[464],
        retainerCity: struct.data[465],
        dyeId: MachinaModels.getUint16(struct.data, 466),
    };
    struct.listing_7 = {
        listingId: MachinaModels.getUint64(struct.data, 468),
        retainerId: MachinaModels.getUint64(struct.data, 476),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 484),
        artisanId: MachinaModels.getUint64(struct.data, 492),
        pricePerUnit: MachinaModels.getUint32(struct.data, 500),
        totalTax: MachinaModels.getUint32(struct.data, 504),
        itemQuantity: MachinaModels.getUint32(struct.data, 508),
        itemId: MachinaModels.getUint32(struct.data, 512),
        lastReviewTime: MachinaModels.getUint16(struct.data, 516),
        containerId: MachinaModels.getUint16(struct.data, 518),
        slotId: MachinaModels.getUint32(struct.data, 520),
        durability: MachinaModels.getUint16(struct.data, 524),
        spiritBond: MachinaModels.getUint16(struct.data, 526),
        materiaValue_1: MachinaModels.getUint16(struct.data, 528),materiaValue_2: MachinaModels.getUint16(struct.data, 530),materiaValue_3: MachinaModels.getUint16(struct.data, 532),materiaValue_4: MachinaModels.getUint16(struct.data, 534),materiaValue_5: MachinaModels.getUint16(struct.data, 536),
        retainerName: String.fromCodePoint(struct.data.slice(538, 539)),
        playerName: String.fromCodePoint(struct.data.slice(539, 540)),
        hq: struct.data[540],
        materiaCount: struct.data[541],
        onMannequin: struct.data[542],
        retainerCity: struct.data[543],
        dyeId: MachinaModels.getUint16(struct.data, 544),
    };
    struct.listing_8 = {
        listingId: MachinaModels.getUint64(struct.data, 546),
        retainerId: MachinaModels.getUint64(struct.data, 554),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 562),
        artisanId: MachinaModels.getUint64(struct.data, 570),
        pricePerUnit: MachinaModels.getUint32(struct.data, 578),
        totalTax: MachinaModels.getUint32(struct.data, 582),
        itemQuantity: MachinaModels.getUint32(struct.data, 586),
        itemId: MachinaModels.getUint32(struct.data, 590),
        lastReviewTime: MachinaModels.getUint16(struct.data, 594),
        containerId: MachinaModels.getUint16(struct.data, 596),
        slotId: MachinaModels.getUint32(struct.data, 598),
        durability: MachinaModels.getUint16(struct.data, 602),
        spiritBond: MachinaModels.getUint16(struct.data, 604),
        materiaValue_1: MachinaModels.getUint16(struct.data, 606),materiaValue_2: MachinaModels.getUint16(struct.data, 608),materiaValue_3: MachinaModels.getUint16(struct.data, 610),materiaValue_4: MachinaModels.getUint16(struct.data, 612),materiaValue_5: MachinaModels.getUint16(struct.data, 614),
        retainerName: String.fromCodePoint(struct.data.slice(616, 617)),
        playerName: String.fromCodePoint(struct.data.slice(617, 618)),
        hq: struct.data[618],
        materiaCount: struct.data[619],
        onMannequin: struct.data[620],
        retainerCity: struct.data[621],
        dyeId: MachinaModels.getUint16(struct.data, 622),
    };
    struct.listing_9 = {
        listingId: MachinaModels.getUint64(struct.data, 624),
        retainerId: MachinaModels.getUint64(struct.data, 632),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 640),
        artisanId: MachinaModels.getUint64(struct.data, 648),
        pricePerUnit: MachinaModels.getUint32(struct.data, 656),
        totalTax: MachinaModels.getUint32(struct.data, 660),
        itemQuantity: MachinaModels.getUint32(struct.data, 664),
        itemId: MachinaModels.getUint32(struct.data, 668),
        lastReviewTime: MachinaModels.getUint16(struct.data, 672),
        containerId: MachinaModels.getUint16(struct.data, 674),
        slotId: MachinaModels.getUint32(struct.data, 676),
        durability: MachinaModels.getUint16(struct.data, 680),
        spiritBond: MachinaModels.getUint16(struct.data, 682),
        materiaValue_1: MachinaModels.getUint16(struct.data, 684),materiaValue_2: MachinaModels.getUint16(struct.data, 686),materiaValue_3: MachinaModels.getUint16(struct.data, 688),materiaValue_4: MachinaModels.getUint16(struct.data, 690),materiaValue_5: MachinaModels.getUint16(struct.data, 692),
        retainerName: String.fromCodePoint(struct.data.slice(694, 695)),
        playerName: String.fromCodePoint(struct.data.slice(695, 696)),
        hq: struct.data[696],
        materiaCount: struct.data[697],
        onMannequin: struct.data[698],
        retainerCity: struct.data[699],
        dyeId: MachinaModels.getUint16(struct.data, 700),
    };
    struct.listing_10 = {
        listingId: MachinaModels.getUint64(struct.data, 702),
        retainerId: MachinaModels.getUint64(struct.data, 710),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 718),
        artisanId: MachinaModels.getUint64(struct.data, 726),
        pricePerUnit: MachinaModels.getUint32(struct.data, 734),
        totalTax: MachinaModels.getUint32(struct.data, 738),
        itemQuantity: MachinaModels.getUint32(struct.data, 742),
        itemId: MachinaModels.getUint32(struct.data, 746),
        lastReviewTime: MachinaModels.getUint16(struct.data, 750),
        containerId: MachinaModels.getUint16(struct.data, 752),
        slotId: MachinaModels.getUint32(struct.data, 754),
        durability: MachinaModels.getUint16(struct.data, 758),
        spiritBond: MachinaModels.getUint16(struct.data, 760),
        materiaValue_1: MachinaModels.getUint16(struct.data, 762),materiaValue_2: MachinaModels.getUint16(struct.data, 764),materiaValue_3: MachinaModels.getUint16(struct.data, 766),materiaValue_4: MachinaModels.getUint16(struct.data, 768),materiaValue_5: MachinaModels.getUint16(struct.data, 770),
        retainerName: String.fromCodePoint(struct.data.slice(772, 773)),
        playerName: String.fromCodePoint(struct.data.slice(773, 774)),
        hq: struct.data[774],
        materiaCount: struct.data[775],
        onMannequin: struct.data[776],
        retainerCity: struct.data[777],
        dyeId: MachinaModels.getUint16(struct.data, 778),
    };
    struct.listingId = MachinaModels.getUint64(struct.data, 780);
    struct.retainerId = MachinaModels.getUint64(struct.data, 788);
    struct.retainerOwnerId = MachinaModels.getUint64(struct.data, 796);
    struct.artisanId = MachinaModels.getUint64(struct.data, 804);
    struct.pricePerUnit = MachinaModels.getUint32(struct.data, 812);
    struct.totalTax = MachinaModels.getUint32(struct.data, 816);
    struct.itemQuantity = MachinaModels.getUint32(struct.data, 820);
    struct.itemId = MachinaModels.getUint32(struct.data, 824);
    struct.lastReviewTime = MachinaModels.getUint16(struct.data, 828);
    struct.containerId = MachinaModels.getUint16(struct.data, 830);
    struct.slotId = MachinaModels.getUint32(struct.data, 832);
    struct.durability = MachinaModels.getUint16(struct.data, 836);
    struct.spiritBond = MachinaModels.getUint16(struct.data, 838);
    struct.materiaValue_1 = MachinaModels.getUint16(struct.data, 840);    struct.materiaValue_2 = MachinaModels.getUint16(struct.data, 842);    struct.materiaValue_3 = MachinaModels.getUint16(struct.data, 844);    struct.materiaValue_4 = MachinaModels.getUint16(struct.data, 846);    struct.materiaValue_5 = MachinaModels.getUint16(struct.data, 848);
    struct.retainerName = String.fromCodePoint(struct.data.slice(850, 851));
    struct.playerName = String.fromCodePoint(struct.data.slice(851, 852));
    struct.hq = struct.data[852];
    struct.materiaCount = struct.data[853];
    struct.onMannequin = struct.data[854];
    struct.retainerCity = struct.data[855];
    struct.dyeId = MachinaModels.getUint16(struct.data, 856);
    struct.listingIndexEnd = struct.data[858];
    struct.listingIndexStart = struct.data[859];
    struct.requestId = MachinaModels.getUint16(struct.data, 860);
};