// This is an auto-generated file.

const MachinaModels = require("../_MachinaModels.js")

module.exports = async (struct) => {
    struct.listing_1 = {
        listingId: MachinaModels.getUint64(struct.data, 0),
        retainerId: MachinaModels.getUint64(struct.data, 8),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 16),
        artisanId: MachinaModels.getUint64(struct.data, 24),
        pricePerUnit: MachinaModels.getUint32(struct.data, 32),
        totalTax: MachinaModels.getUint32(struct.data, 36),
        itemQuantity: MachinaModels.getUint32(struct.data, 40),
        itemId: MachinaModels.getUint32(struct.data, 44),
        lastReviewTime: MachinaModels.getUint16(struct.data, 48),
        containerId: MachinaModels.getUint16(struct.data, 50),
        slotId: MachinaModels.getUint32(struct.data, 52),
        durability: MachinaModels.getUint16(struct.data, 56),
        spiritBond: MachinaModels.getUint16(struct.data, 58),
        materiaValue_1: MachinaModels.getUint16(struct.data, 60),materiaValue_2: MachinaModels.getUint16(struct.data, 60),materiaValue_3: MachinaModels.getUint16(struct.data, 60),materiaValue_4: MachinaModels.getUint16(struct.data, 60),materiaValue_5: MachinaModels.getUint16(struct.data, 60),
        retainerName: String.fromCodePoint(struct.data.slice(76, 108)),
        playerName: String.fromCodePoint(struct.data.slice(108, 140)),
        hq: struct.data[140],
        materiaCount: struct.data[141],
        onMannequin: struct.data[142],
        retainerCity: struct.data[143],
        dyeId: MachinaModels.getUint16(struct.data, 144),
    };
    struct.listing_2 = {
        listingId: MachinaModels.getUint64(struct.data, 152),
        retainerId: MachinaModels.getUint64(struct.data, 160),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 168),
        artisanId: MachinaModels.getUint64(struct.data, 176),
        pricePerUnit: MachinaModels.getUint32(struct.data, 184),
        totalTax: MachinaModels.getUint32(struct.data, 188),
        itemQuantity: MachinaModels.getUint32(struct.data, 192),
        itemId: MachinaModels.getUint32(struct.data, 196),
        lastReviewTime: MachinaModels.getUint16(struct.data, 200),
        containerId: MachinaModels.getUint16(struct.data, 202),
        slotId: MachinaModels.getUint32(struct.data, 204),
        durability: MachinaModels.getUint16(struct.data, 208),
        spiritBond: MachinaModels.getUint16(struct.data, 210),
        materiaValue_1: MachinaModels.getUint16(struct.data, 212),materiaValue_2: MachinaModels.getUint16(struct.data, 212),materiaValue_3: MachinaModels.getUint16(struct.data, 212),materiaValue_4: MachinaModels.getUint16(struct.data, 212),materiaValue_5: MachinaModels.getUint16(struct.data, 212),
        retainerName: String.fromCodePoint(struct.data.slice(228, 260)),
        playerName: String.fromCodePoint(struct.data.slice(260, 292)),
        hq: struct.data[292],
        materiaCount: struct.data[293],
        onMannequin: struct.data[294],
        retainerCity: struct.data[295],
        dyeId: MachinaModels.getUint16(struct.data, 296),
    };
    struct.listing_3 = {
        listingId: MachinaModels.getUint64(struct.data, 304),
        retainerId: MachinaModels.getUint64(struct.data, 312),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 320),
        artisanId: MachinaModels.getUint64(struct.data, 328),
        pricePerUnit: MachinaModels.getUint32(struct.data, 336),
        totalTax: MachinaModels.getUint32(struct.data, 340),
        itemQuantity: MachinaModels.getUint32(struct.data, 344),
        itemId: MachinaModels.getUint32(struct.data, 348),
        lastReviewTime: MachinaModels.getUint16(struct.data, 352),
        containerId: MachinaModels.getUint16(struct.data, 354),
        slotId: MachinaModels.getUint32(struct.data, 356),
        durability: MachinaModels.getUint16(struct.data, 360),
        spiritBond: MachinaModels.getUint16(struct.data, 362),
        materiaValue_1: MachinaModels.getUint16(struct.data, 364),materiaValue_2: MachinaModels.getUint16(struct.data, 364),materiaValue_3: MachinaModels.getUint16(struct.data, 364),materiaValue_4: MachinaModels.getUint16(struct.data, 364),materiaValue_5: MachinaModels.getUint16(struct.data, 364),
        retainerName: String.fromCodePoint(struct.data.slice(380, 412)),
        playerName: String.fromCodePoint(struct.data.slice(412, 444)),
        hq: struct.data[444],
        materiaCount: struct.data[445],
        onMannequin: struct.data[446],
        retainerCity: struct.data[447],
        dyeId: MachinaModels.getUint16(struct.data, 448),
    };
    struct.listing_4 = {
        listingId: MachinaModels.getUint64(struct.data, 456),
        retainerId: MachinaModels.getUint64(struct.data, 464),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 472),
        artisanId: MachinaModels.getUint64(struct.data, 480),
        pricePerUnit: MachinaModels.getUint32(struct.data, 488),
        totalTax: MachinaModels.getUint32(struct.data, 492),
        itemQuantity: MachinaModels.getUint32(struct.data, 496),
        itemId: MachinaModels.getUint32(struct.data, 500),
        lastReviewTime: MachinaModels.getUint16(struct.data, 504),
        containerId: MachinaModels.getUint16(struct.data, 506),
        slotId: MachinaModels.getUint32(struct.data, 508),
        durability: MachinaModels.getUint16(struct.data, 512),
        spiritBond: MachinaModels.getUint16(struct.data, 514),
        materiaValue_1: MachinaModels.getUint16(struct.data, 516),materiaValue_2: MachinaModels.getUint16(struct.data, 516),materiaValue_3: MachinaModels.getUint16(struct.data, 516),materiaValue_4: MachinaModels.getUint16(struct.data, 516),materiaValue_5: MachinaModels.getUint16(struct.data, 516),
        retainerName: String.fromCodePoint(struct.data.slice(532, 564)),
        playerName: String.fromCodePoint(struct.data.slice(564, 596)),
        hq: struct.data[596],
        materiaCount: struct.data[597],
        onMannequin: struct.data[598],
        retainerCity: struct.data[599],
        dyeId: MachinaModels.getUint16(struct.data, 600),
    };
    struct.listing_5 = {
        listingId: MachinaModels.getUint64(struct.data, 608),
        retainerId: MachinaModels.getUint64(struct.data, 616),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 624),
        artisanId: MachinaModels.getUint64(struct.data, 632),
        pricePerUnit: MachinaModels.getUint32(struct.data, 640),
        totalTax: MachinaModels.getUint32(struct.data, 644),
        itemQuantity: MachinaModels.getUint32(struct.data, 648),
        itemId: MachinaModels.getUint32(struct.data, 652),
        lastReviewTime: MachinaModels.getUint16(struct.data, 656),
        containerId: MachinaModels.getUint16(struct.data, 658),
        slotId: MachinaModels.getUint32(struct.data, 660),
        durability: MachinaModels.getUint16(struct.data, 664),
        spiritBond: MachinaModels.getUint16(struct.data, 666),
        materiaValue_1: MachinaModels.getUint16(struct.data, 668),materiaValue_2: MachinaModels.getUint16(struct.data, 668),materiaValue_3: MachinaModels.getUint16(struct.data, 668),materiaValue_4: MachinaModels.getUint16(struct.data, 668),materiaValue_5: MachinaModels.getUint16(struct.data, 668),
        retainerName: String.fromCodePoint(struct.data.slice(684, 716)),
        playerName: String.fromCodePoint(struct.data.slice(716, 748)),
        hq: struct.data[748],
        materiaCount: struct.data[749],
        onMannequin: struct.data[750],
        retainerCity: struct.data[751],
        dyeId: MachinaModels.getUint16(struct.data, 752),
    };
    struct.listing_6 = {
        listingId: MachinaModels.getUint64(struct.data, 760),
        retainerId: MachinaModels.getUint64(struct.data, 768),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 776),
        artisanId: MachinaModels.getUint64(struct.data, 784),
        pricePerUnit: MachinaModels.getUint32(struct.data, 792),
        totalTax: MachinaModels.getUint32(struct.data, 796),
        itemQuantity: MachinaModels.getUint32(struct.data, 800),
        itemId: MachinaModels.getUint32(struct.data, 804),
        lastReviewTime: MachinaModels.getUint16(struct.data, 808),
        containerId: MachinaModels.getUint16(struct.data, 810),
        slotId: MachinaModels.getUint32(struct.data, 812),
        durability: MachinaModels.getUint16(struct.data, 816),
        spiritBond: MachinaModels.getUint16(struct.data, 818),
        materiaValue_1: MachinaModels.getUint16(struct.data, 820),materiaValue_2: MachinaModels.getUint16(struct.data, 820),materiaValue_3: MachinaModels.getUint16(struct.data, 820),materiaValue_4: MachinaModels.getUint16(struct.data, 820),materiaValue_5: MachinaModels.getUint16(struct.data, 820),
        retainerName: String.fromCodePoint(struct.data.slice(836, 868)),
        playerName: String.fromCodePoint(struct.data.slice(868, 900)),
        hq: struct.data[900],
        materiaCount: struct.data[901],
        onMannequin: struct.data[902],
        retainerCity: struct.data[903],
        dyeId: MachinaModels.getUint16(struct.data, 904),
    };
    struct.listing_7 = {
        listingId: MachinaModels.getUint64(struct.data, 912),
        retainerId: MachinaModels.getUint64(struct.data, 920),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 928),
        artisanId: MachinaModels.getUint64(struct.data, 936),
        pricePerUnit: MachinaModels.getUint32(struct.data, 944),
        totalTax: MachinaModels.getUint32(struct.data, 948),
        itemQuantity: MachinaModels.getUint32(struct.data, 952),
        itemId: MachinaModels.getUint32(struct.data, 956),
        lastReviewTime: MachinaModels.getUint16(struct.data, 960),
        containerId: MachinaModels.getUint16(struct.data, 962),
        slotId: MachinaModels.getUint32(struct.data, 964),
        durability: MachinaModels.getUint16(struct.data, 968),
        spiritBond: MachinaModels.getUint16(struct.data, 970),
        materiaValue_1: MachinaModels.getUint16(struct.data, 972),materiaValue_2: MachinaModels.getUint16(struct.data, 972),materiaValue_3: MachinaModels.getUint16(struct.data, 972),materiaValue_4: MachinaModels.getUint16(struct.data, 972),materiaValue_5: MachinaModels.getUint16(struct.data, 972),
        retainerName: String.fromCodePoint(struct.data.slice(988, 1020)),
        playerName: String.fromCodePoint(struct.data.slice(1020, 1052)),
        hq: struct.data[1052],
        materiaCount: struct.data[1053],
        onMannequin: struct.data[1054],
        retainerCity: struct.data[1055],
        dyeId: MachinaModels.getUint16(struct.data, 1056),
    };
    struct.listing_8 = {
        listingId: MachinaModels.getUint64(struct.data, 1064),
        retainerId: MachinaModels.getUint64(struct.data, 1072),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 1080),
        artisanId: MachinaModels.getUint64(struct.data, 1088),
        pricePerUnit: MachinaModels.getUint32(struct.data, 1096),
        totalTax: MachinaModels.getUint32(struct.data, 1100),
        itemQuantity: MachinaModels.getUint32(struct.data, 1104),
        itemId: MachinaModels.getUint32(struct.data, 1108),
        lastReviewTime: MachinaModels.getUint16(struct.data, 1112),
        containerId: MachinaModels.getUint16(struct.data, 1114),
        slotId: MachinaModels.getUint32(struct.data, 1116),
        durability: MachinaModels.getUint16(struct.data, 1120),
        spiritBond: MachinaModels.getUint16(struct.data, 1122),
        materiaValue_1: MachinaModels.getUint16(struct.data, 1124),materiaValue_2: MachinaModels.getUint16(struct.data, 1124),materiaValue_3: MachinaModels.getUint16(struct.data, 1124),materiaValue_4: MachinaModels.getUint16(struct.data, 1124),materiaValue_5: MachinaModels.getUint16(struct.data, 1124),
        retainerName: String.fromCodePoint(struct.data.slice(1140, 1172)),
        playerName: String.fromCodePoint(struct.data.slice(1172, 1204)),
        hq: struct.data[1204],
        materiaCount: struct.data[1205],
        onMannequin: struct.data[1206],
        retainerCity: struct.data[1207],
        dyeId: MachinaModels.getUint16(struct.data, 1208),
    };
    struct.listing_9 = {
        listingId: MachinaModels.getUint64(struct.data, 1216),
        retainerId: MachinaModels.getUint64(struct.data, 1224),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 1232),
        artisanId: MachinaModels.getUint64(struct.data, 1240),
        pricePerUnit: MachinaModels.getUint32(struct.data, 1248),
        totalTax: MachinaModels.getUint32(struct.data, 1252),
        itemQuantity: MachinaModels.getUint32(struct.data, 1256),
        itemId: MachinaModels.getUint32(struct.data, 1260),
        lastReviewTime: MachinaModels.getUint16(struct.data, 1264),
        containerId: MachinaModels.getUint16(struct.data, 1266),
        slotId: MachinaModels.getUint32(struct.data, 1268),
        durability: MachinaModels.getUint16(struct.data, 1272),
        spiritBond: MachinaModels.getUint16(struct.data, 1274),
        materiaValue_1: MachinaModels.getUint16(struct.data, 1276),materiaValue_2: MachinaModels.getUint16(struct.data, 1276),materiaValue_3: MachinaModels.getUint16(struct.data, 1276),materiaValue_4: MachinaModels.getUint16(struct.data, 1276),materiaValue_5: MachinaModels.getUint16(struct.data, 1276),
        retainerName: String.fromCodePoint(struct.data.slice(1292, 1324)),
        playerName: String.fromCodePoint(struct.data.slice(1324, 1356)),
        hq: struct.data[1356],
        materiaCount: struct.data[1357],
        onMannequin: struct.data[1358],
        retainerCity: struct.data[1359],
        dyeId: MachinaModels.getUint16(struct.data, 1360),
    };
    struct.listing_10 = {
        listingId: MachinaModels.getUint64(struct.data, 1368),
        retainerId: MachinaModels.getUint64(struct.data, 1376),
        retainerOwnerId: MachinaModels.getUint64(struct.data, 1384),
        artisanId: MachinaModels.getUint64(struct.data, 1392),
        pricePerUnit: MachinaModels.getUint32(struct.data, 1400),
        totalTax: MachinaModels.getUint32(struct.data, 1404),
        itemQuantity: MachinaModels.getUint32(struct.data, 1408),
        itemId: MachinaModels.getUint32(struct.data, 1412),
        lastReviewTime: MachinaModels.getUint16(struct.data, 1416),
        containerId: MachinaModels.getUint16(struct.data, 1418),
        slotId: MachinaModels.getUint32(struct.data, 1420),
        durability: MachinaModels.getUint16(struct.data, 1424),
        spiritBond: MachinaModels.getUint16(struct.data, 1426),
        materiaValue_1: MachinaModels.getUint16(struct.data, 1428),materiaValue_2: MachinaModels.getUint16(struct.data, 1428),materiaValue_3: MachinaModels.getUint16(struct.data, 1428),materiaValue_4: MachinaModels.getUint16(struct.data, 1428),materiaValue_5: MachinaModels.getUint16(struct.data, 1428),
        retainerName: String.fromCodePoint(struct.data.slice(1444, 1476)),
        playerName: String.fromCodePoint(struct.data.slice(1476, 1508)),
        hq: struct.data[1508],
        materiaCount: struct.data[1509],
        onMannequin: struct.data[1510],
        retainerCity: struct.data[1511],
        dyeId: MachinaModels.getUint16(struct.data, 1512),
    };
    struct.listingId = MachinaModels.getUint64(struct.data, 1520);
    struct.retainerId = MachinaModels.getUint64(struct.data, 1528);
    struct.retainerOwnerId = MachinaModels.getUint64(struct.data, 1536);
    struct.artisanId = MachinaModels.getUint64(struct.data, 1544);
    struct.pricePerUnit = MachinaModels.getUint32(struct.data, 1552);
    struct.totalTax = MachinaModels.getUint32(struct.data, 1556);
    struct.itemQuantity = MachinaModels.getUint32(struct.data, 1560);
    struct.itemId = MachinaModels.getUint32(struct.data, 1564);
    struct.lastReviewTime = MachinaModels.getUint16(struct.data, 1568);
    struct.containerId = MachinaModels.getUint16(struct.data, 1570);
    struct.slotId = MachinaModels.getUint32(struct.data, 1572);
    struct.durability = MachinaModels.getUint16(struct.data, 1576);
    struct.spiritBond = MachinaModels.getUint16(struct.data, 1578);
    struct.materiaValue_1 = MachinaModels.getUint16(struct.data, 1580);    struct.materiaValue_2 = MachinaModels.getUint16(struct.data, 1580);    struct.materiaValue_3 = MachinaModels.getUint16(struct.data, 1580);    struct.materiaValue_4 = MachinaModels.getUint16(struct.data, 1580);    struct.materiaValue_5 = MachinaModels.getUint16(struct.data, 1580);
    struct.retainerName = String.fromCodePoint(struct.data.slice(1596, 1628));
    struct.playerName = String.fromCodePoint(struct.data.slice(1628, 1660));
    struct.hq = struct.data[1660];
    struct.materiaCount = struct.data[1661];
    struct.onMannequin = struct.data[1662];
    struct.retainerCity = struct.data[1663];
    struct.dyeId = MachinaModels.getUint16(struct.data, 1664);
    struct.listingIndexEnd = struct.data[1672];
    struct.listingIndexStart = struct.data[1673];
    struct.requestId = MachinaModels.getUint16(struct.data, 1674);
};