// This is an auto-generated file.

const MachinaModels = require("../_MachinaModels.js")

module.exports = async (struct) => {
    struct.gimmickId = MachinaModels.getUint32(struct.data, 0);
    struct.u2b = struct.data[4];
    struct.u2ab = struct.data[5];
    struct.gmRank = struct.data[6];
    struct.u3b = struct.data[7];
    struct.aggressionMode = struct.data[8];
    struct.onlineStatus = struct.data[9];
    struct.u3c = struct.data[10];
    struct.pose = struct.data[11];
    struct.u4 = MachinaModels.getUint32(struct.data, 12);
    struct.targetId = MachinaModels.getUint64(struct.data, 16);
    struct.u6 = MachinaModels.getUint32(struct.data, 24);
    struct.u7 = MachinaModels.getUint32(struct.data, 28);
    struct.mainWeaponModel = MachinaModels.getUint64(struct.data, 32);
    struct.secWeaponModel = MachinaModels.getUint64(struct.data, 40);
    struct.craftToolModel = MachinaModels.getUint64(struct.data, 48);
    struct.u14 = MachinaModels.getUint32(struct.data, 56);
    struct.u15 = MachinaModels.getUint32(struct.data, 60);
    struct.bNPCBase = MachinaModels.getUint32(struct.data, 64);
    struct.bNPCName = MachinaModels.getUint32(struct.data, 68);
    struct.levelId = MachinaModels.getUint32(struct.data, 72);
    struct.u19 = MachinaModels.getUint32(struct.data, 76);
    struct.directorId = MachinaModels.getUint32(struct.data, 80);
    struct.spawnerId = MachinaModels.getUint32(struct.data, 84);
    struct.parentActorId = MachinaModels.getUint32(struct.data, 88);
    struct.hPMax = MachinaModels.getUint32(struct.data, 92);
    struct.hPCurr = MachinaModels.getUint32(struct.data, 96);
    struct.displayFlags = MachinaModels.getUint32(struct.data, 100);
    struct.fateID = MachinaModels.getUint16(struct.data, 104);
    struct.mPCurr = MachinaModels.getUint16(struct.data, 106);
    struct.tPCurr = MachinaModels.getUint16(struct.data, 108);
    struct.mPMax = MachinaModels.getUint16(struct.data, 110);
    struct.tPMax = MachinaModels.getUint16(struct.data, 112);
    struct.modelChara = MachinaModels.getUint16(struct.data, 114);
    struct.rotation = MachinaModels.getUint16(struct.data, 116);
    struct.activeMinion = MachinaModels.getUint16(struct.data, 118);
    struct.spawnIndex = struct.data[120];
    struct.state = struct.data[121];
    struct.persistantEmote = struct.data[122];
    struct.modelType = struct.data[123];
    struct.subtype = struct.data[124];
    struct.voice = struct.data[125];
    struct.u25c = MachinaModels.getUint16(struct.data, 126);
    struct.enemyType = struct.data[128];
    struct.level = struct.data[129];
    struct.classJob = struct.data[130];
    struct.u26d = struct.data[131];
    struct.u27a = MachinaModels.getUint16(struct.data, 132);
    struct.currentMount = struct.data[134];
    struct.mountHead = struct.data[135];
    struct.mountBody = struct.data[136];
    struct.mountFeet = struct.data[137];
    struct.mountColor = struct.data[138];
    struct.scale = struct.data[139];
    struct.elementalLevel = MachinaModels.getUint16(struct.data, 140);
    struct.element = MachinaModels.getUint16(struct.data, 142);
    struct.u30b = MachinaModels.getUint32(struct.data, 144);
    struct.effect_1 = MachinaModels.getUint16(struct.data, 148);    struct.effect_2 = MachinaModels.getUint16(struct.data, 148);    struct.effect_3 = MachinaModels.getUint16(struct.data, 148);    struct.effect_4 = MachinaModels.getUint16(struct.data, 148);    struct.effect_5 = MachinaModels.getUint16(struct.data, 148);    struct.effect_6 = MachinaModels.getUint16(struct.data, 148);    struct.effect_7 = MachinaModels.getUint16(struct.data, 148);    struct.effect_8 = MachinaModels.getUint16(struct.data, 148);    struct.effect_9 = MachinaModels.getUint16(struct.data, 148);    struct.effect_10 = MachinaModels.getUint16(struct.data, 148);    struct.effect_11 = MachinaModels.getUint16(struct.data, 148);    struct.effect_12 = MachinaModels.getUint16(struct.data, 148);    struct.effect_13 = MachinaModels.getUint16(struct.data, 148);    struct.effect_14 = MachinaModels.getUint16(struct.data, 148);    struct.effect_15 = MachinaModels.getUint16(struct.data, 148);    struct.effect_16 = MachinaModels.getUint16(struct.data, 148);    struct.effect_17 = MachinaModels.getUint16(struct.data, 148);    struct.effect_18 = MachinaModels.getUint16(struct.data, 148);    struct.effect_19 = MachinaModels.getUint16(struct.data, 148);    struct.effect_20 = MachinaModels.getUint16(struct.data, 148);    struct.effect_21 = MachinaModels.getUint16(struct.data, 148);    struct.effect_22 = MachinaModels.getUint16(struct.data, 148);    struct.effect_23 = MachinaModels.getUint16(struct.data, 148);    struct.effect_24 = MachinaModels.getUint16(struct.data, 148);    struct.effect_25 = MachinaModels.getUint16(struct.data, 148);    struct.effect_26 = MachinaModels.getUint16(struct.data, 148);    struct.effect_27 = MachinaModels.getUint16(struct.data, 148);    struct.effect_28 = MachinaModels.getUint16(struct.data, 148);    struct.effect_29 = MachinaModels.getUint16(struct.data, 148);    struct.effect_30 = MachinaModels.getUint16(struct.data, 148);
    struct.pos = MachinaModels.getUint16(struct.data, 208);
    struct.models_1 = MachinaModels.getUint32(struct.data, 210);    struct.models_2 = MachinaModels.getUint32(struct.data, 210);    struct.models_3 = MachinaModels.getUint32(struct.data, 210);    struct.models_4 = MachinaModels.getUint32(struct.data, 210);    struct.models_5 = MachinaModels.getUint32(struct.data, 210);    struct.models_6 = MachinaModels.getUint32(struct.data, 210);    struct.models_7 = MachinaModels.getUint32(struct.data, 210);    struct.models_8 = MachinaModels.getUint32(struct.data, 210);    struct.models_9 = MachinaModels.getUint32(struct.data, 210);    struct.models_10 = MachinaModels.getUint32(struct.data, 210);
    struct.name = String.fromCodePoint(struct.data.slice(250, 282));
    struct.look_1 = struct.data[282];    struct.look_2 = struct.data[282];    struct.look_3 = struct.data[282];    struct.look_4 = struct.data[282];    struct.look_5 = struct.data[282];    struct.look_6 = struct.data[282];    struct.look_7 = struct.data[282];    struct.look_8 = struct.data[282];    struct.look_9 = struct.data[282];    struct.look_10 = struct.data[282];    struct.look_11 = struct.data[282];    struct.look_12 = struct.data[282];    struct.look_13 = struct.data[282];    struct.look_14 = struct.data[282];    struct.look_15 = struct.data[282];    struct.look_16 = struct.data[282];    struct.look_17 = struct.data[282];    struct.look_18 = struct.data[282];    struct.look_19 = struct.data[282];    struct.look_20 = struct.data[282];    struct.look_21 = struct.data[282];    struct.look_22 = struct.data[282];    struct.look_23 = struct.data[282];    struct.look_24 = struct.data[282];    struct.look_25 = struct.data[282];    struct.look_26 = struct.data[282];
    struct.fcTag = String.fromCodePoint(struct.data.slice(308, 314));
    struct.bNPCPartSlot = struct.data[322];
};