module.exports = {
    // https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Common.h#L731-L834
    chatType: [
        "LogKindError",
        "ServerDebug",
        "ServerUrgent",
        "ServerNotice",
        "Unused4",
        "Unused5",
        "Unused6",
        "Unused7",
        "Unused8",
        "Unused9",
        "Say",
        "Shout",
        "Tell",
        "TellReceive",
        "Party",
        "Alliance",
        "LS1",
        "LS2",
        "LS3",
        "LS4",
        "LS5",
        "LS6",
        "LS7",
        "LS8",
        "FreeCompany",
        "Unused25",
        "Unused26",
        "NoviceNetwork",
        "CustomEmote",
        "StandardEmote",
        "Yell",
        "Unknown31",
        "PartyUnk2",
        "Unused33",
        "Unused34",
        "Unused35",
        "Unused36",
        "Unused37",
        "Unused38",
        "Unused39",
        "Unused40",
        "BattleDamage",
        "BattleFailed",
        "BattleActions",
        "BattleItems",
        "BattleHealing",
        "BattleBeneficial",
        "BattleDetrimental",
        "BattleUnk48",
        "BattleUnk49",
        "Unused50",
        "Unused51",
        "Unused52",
        "Unused53",
        "Unused54",
        "Unused55",
        "Echo",
        "SystemMessage",
        "SystemErrorMessage",
        "BattleSystem",
        "GatheringSystem",
        "NPCMessage",
        "LootMessage",
        "Unused63",
        "CharProgress",
        "Loot",
        "Crafting",
        "Gathering",
        "NPCAnnouncement",
        "FCAnnouncement",
        "FCLogin",
        "RetainerSale",
        "PartySearch",
        "PCSign",
        "DiceRoll",
        "NoviceNetworkNotice",
        "Unknown76",
        "Unused77",
        "Unused78",
        "Unused79",
        "GMTell",
        "GMSay",
        "GMShout",
        "GMYell",
        "GMParty",
        "GMFreeCompany",
        "GMLS1",
        "GMLS2",
        "GMLS3",
        "GMLS4",
        "GMLS5",
        "GMLS6",
        "GMLS7",
        "GMLS8",
        "GMNoviceNetwork",
        "Unused95",
        "Unused96",
        "Unused97",
        "Unused98",
        "Unused99",
        "Unused100",
    ],

    cityIDList: {
        0x01: "Limsa Lominsa",
        0x02: "Gridania",
        0x03: "Ul'dah",
        0x04: "Ishgard",
        0x07: "Kugane",
        0x0A: "Crystarium",
    },

    roles: {
        0: "none",
        1: "tank",
        2: "dps",
        3: "rangedDps",
        4: "healer",
    },

    skillType: {
        0x1: "Normal",
        0x2: "ItemAction",
        0xD: "MountSkill",
    },

    actionEffectDisplayType: {
        0: "HideActionName",
        1: "ShowActionName",
        2: "ShowItemName",
    },

    actionHitSeverityType: {
        0: "NormalDamageCritHeal",
        1: "CritDamageNormalHeal",
        2: "DirectHitDamage",
        3: "CriticalDirectHitDamage",

    },
};
